# Generated by Django 5.2.12 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="Base system prompt for the travel assistant. User and party travel preferences are appended automatically."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat System Prompt",
                "verbose_name_plural": "Chat System Prompt",
            },
        ),
    ]
