name: Test Frontend

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: check frontend
        working-directory: frontend
        run: bun run check

      - name: build frontend
        working-directory: frontend
        run: bun run build
